name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]

body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      phaceholder: Write here
    validations:
      required: true
  
  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      phaceholder: Write here
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        **Screenshots**
        *If applicable, add screenshots to help explain your problem.*

  - type: textarea
    id: server-info
    attributes:
      label: Server info
      description: Information about installed server *(please complete the following information)*.
      phaceholder: |
        example:
          - **OS:** Windows
          - **Version:** 0.0.1a1.dev1
      value: |
        - **OS:** [Your os, e.g. Windows]
        - **Version:** [Server version, e.g. 0.0.1a1.dev1]
    validations:
      required: true

  - type: textarea
    id: web-info
    attributes:
      label: WebPanel info
      description: Information about webpanel *(please complete the following information)*.
      phaceholder: |
        example:
          - **Browser:** Google Chrome
          - **Theme:** Dark
          - **Language:** Russian (Русский)
      value: |
        - **Browser:** [Your browser, e.g. Google Chrome]
        - **Theme:** [Theme, e.g. Dark]
        - **Language:** [WebPanel language on your user, e.g. Russian (Русский)]

  - type: textarea
    id: logs
    attributes:
      label: Server logs
      description: Logs of server from `<server directory>/data/logs/latest.log`.
      render: shell