database: # Database settings
  network: # Network settings
    host: "localhost" # DB Host
    port: 2993 # DB Port
  dataFolder: "./data" # Storage (data) folder

admin: # SyrDB Admin settings
  enable: true # Listen the http connections & display SyrDB Admin
  users: # Admin auth users
    - username: "root" # Example user name
      password: "root" # Example user password
      permissions: admin # Example user permissions

logger: # Logger settings
  console: # Logging to console
    enable: true # Do I need to use logging
    level: DEBUG # Logger level, available: INFO, WARN, ERROR or DEBUG
  database: # Logging to logs database
    enable: false
    level: DEBUG
    name: "logs" # Database name
  file: # Logging to file
    enable: true
    level: DEBUG
    folder: "logs" # File folder, null = "."
    filename: "DD.MM.YYYY.log" # File name, supports time placeholders
    loggingFormat: sdb-journal # File logging format, available: sdb-journal, json or yaml

security: # Security Settings
  auth: # Authorization settings
    enable: true # Whether it is necessary to require authorization from clients
    accessToken: "SOME TEXT" # SyrDB access token
    users: # Users available for authorization
      - username: "root" # Example user name
        password: "root" # Example user password
        permissions: admin # Example user permissions, available: admin, manage, info, read, write or readAndWrite
        db: "$all" # Database available to the example user, $all - to specify all
        maxAuthentications: 1 # Maximum number of authentications in example user at the same time, -1 - infinitely (Not recommended)
  maxConnections: 10 # Max connections to SyrDB, -1 - infinitely

streams: # Streams settings
  enable: false # Whether to use streams
  mode: "auto" # Threads usage mode, available: auto or manually
  autoSettings: # Settings for automatic use of threads
    maxThreads: 10 # Maximum number of threads
  #streamsList:
  #  - id: 0 # Stream id, 0 - main
  #    name: "Main Stream" # Stream name
  #    maxConnections: 1 # Max connections to this stream, -1 - infinitely
  #    forwarding: "$randomForwarding{streams: 1-2}" # Stream forwarding
  #  - id: 1
  #    name: "Stream 1"
  #    maxConnections: -1
  #  - id: 2
  #    name: "Stream 2"
  #    maxConnections: -1
