name: Build SyrDB

on:
  push:
    tags:
      - "v*.*.*"

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: "windows"
            os: windows-latest
            path: "build/src/Release"
            extension: ".exe"

          - name: "linux"
            os: ubuntu-latest
            path: "build/src"
            extension: ""

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DOUTPUT_NAME=syrdb-${{ matrix.name }}

      - name: Build on ${{ matrix.name }}
        run: cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }}

      - name: Test
        working-directory: ${{ github.workspace }}/build
        run: ctest -C ${{ env.BUILD_TYPE }}

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          path: "${{ matrix.path }}/syrdb-${{ matrix.name }}${{ matrix.extension }}"
          name: syrdb-${{ matrix.name }}
          if-no-files-found: error

  publish:
    name: Publish release
    if: ${{  }}
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Get version
        run: |
          VER1=$(grep -oP "[0-9]+\.[0-9]+\.[0-9]+" CMakeLists.txt)
          VER2=$(grep -oP "(a|b|rc)[0-9]+(.dev[0-9]+)?" CMakeLists.txt)
          echo "VERSION=v$VER1$VER2" >> $GITHUB_ENV

      - name: Get changes
        run: |
          python3 -c "print('\n'.join(__import__('re').findall(r'^# v[0-9\.a-zA-Z]+[^#]*$', open('CHANGELOG.md', 'r', encoding='utf8').read(), __import__('re').MULTILINE)[0][:-1].split('\n')[1:]))" > ${{ github.workspace }}-CHANGELOG.txt

      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.workspace }}-CHANGELOG.txt
          tag_name: "${{ env.VERSION }}"
          name: "SyrDB ${{ env.VERSION }}"
          files: |
            LICENSE
            **/syrdb-*